### ISSUE TITLE
Error in processing workflow createindices 

### ISSUE THREAD

**Issue by OERK-Maxymovitz** [maxplanck-ie/snakepipes#504] opened 2019-10-09 13:30 UTC
Hi there! 

I've searched so long, but cannot find a solution. Hope you can help me. When trying to use the workflow createindices, an error occurs: " 'Workflow' object has no attribute 'overwrite_configfile' " 
What can I do? 

Please help.... 

Command line code: 
createIndices -o /home/eva/Dokumente/data/ --genomeURL ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --gtfURL ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz hg38

**Comment by dpryan79** [comment] 2019-10-09 13:36
Which version do you have installed?

**Comment by OERK-Maxymovitz** [comment] 2019-10-09 13:43
conda 4.7.10
Python 3.6.7

**Comment by OERK-Maxymovitz** [comment] 2019-10-09 13:47
I downloaded SnakePipes last week. Cannot find a Version-Number anywhere, sorry

**Comment by dpryan79** [comment] 2019-10-09 13:48
Can you post the entirety of the traceback? I can't reproduce this with version 1.3.0.

**Comment by OERK-Maxymovitz** [comment] 2019-10-09 13:49
(snakePipes) eva@gsu001-HP:~$ createIndices -o /home/eva/Dokumente/data/ --genomeURL ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --gtfURL ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz hg38
AttributeError in line 11 of /home/eva/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/createIndices/Snakefile:
'Workflow' object has no attribute 'overwrite_configfile'
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/createIndices/Snakefile", line 11, in <module>
Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by dpryan79** [comment] 2019-10-09 13:58
Can you post the output of `conda list`? This appears to be a change in the snakemake API.

**Comment by OERK-Maxymovitz** [comment] 2019-10-09 14:01
[conda_list.txt](https://github.com/maxplanck-ie/snakepipes/files/3707744/conda_list.txt)

There you go

**Comment by dpryan79** [comment] 2019-10-09 14:04
Can you try downgrading snakemake to 5.6.0 (`conda install -c conda-forge -c bioconda snakemake=5.6.0`?

**Comment by OERK-Maxymovitz** [comment] 2019-10-09 14:10
Did that - more error codes.... 
`createIndices -o /home/eva/Dokumente/data/ --genomeURL ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --gtfURL ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz hg38
Traceback (most recent call last):
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakemake/__init__.py", line 551, in snakemake
    export_cwl=export_cwl)
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakemake/workflow.py", line 425, in execute
    list_params_changes or list_untracked or delete_all_output or delete_temp_output)
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakemake/persistence.py", line 60, in __init__
    os.makedirs(d, exist_ok=True)
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/eva/anaconda3/envs/snakePipes/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!
![Bildschirmfoto vom 2019-10-09 16-08-56](https://user-images.githubusercontent.com/56352872/66489040-42a81980-eaaf-11e9-99d9-02834bc824d3.png)
`

**Comment by dpryan79** [comment] 2019-10-10 08:14
Please follow the setup instructions: https://snakepipes.readthedocs.io/en/stable/content/setting_up.html#modify-global-options and https://snakepipes.readthedocs.io/en/stable/content/setting_up.html#create-the-conda-environments

**Comment by dpryan79** [comment] 2019-10-10 08:15
The original problem has now been fixed with snakePipes 1.3.1, which I just uploaded.

**Closed by dpryan79** 2019-10-10 08:15 UTC
