### ISSUE TITLE
preprocessing: "EOF marker is absent. The input is probably truncated" + "no such file or directory"

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#573] opened 2020-02-27 13:00 UTC
when running a preprocessing pipeline, I get a warning and an error: 
 
> 1. [W::bgzf_read_block] EOF marker is absent. The input is probably truncated

> 2.  sh: _R1.fastq.gz_optical_duplicatesdeduplicatedFASTQ/sample_1: No such file or directory
    sh: _R1.fastq.gzdeduplicatedFASTQ/sample_1: No such file or directory

```bash
ls preprocessing.config.yaml
```

UMIBarcode: false
UMIDedup: false
UMIDedupOpts: --paired
UMIDedupSep: _
aligner: bowtie2
baseDir: /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes
bcPattern: NNNNCCCCCCCCC
clumpifyMemory: 30G
clumpifyOptions: spany=t adjacent=t
clusterConfig: /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/cluster.yaml
clusterConfigFile: null
configFile: null
createDAG: false
downsample: null
emailAddress: null
emailSender: null
ext: .fastq.gz
fastqc: true
indir: /scratch/adrija/02_projectname/data/chip-seq/test_ChIP/rawfastq
keepTemp: false
local: true
maxJobs: 20
onlySSL: false
optDedupDist: 40
organismsDir: /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms
outdir: /scratch/adrija/02_projectname/data/chip-seq/test_ChIP/fastq_dedup_40
pairedEnd: true
pipeline: preprocessing
reads:
- _R1
- _R2
sampleSheet: /localhome/inst/usr123/analysis/02_projectname/data/chip-seq/test_ChIP/rawfastq/samples.tsv
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes'
tempDir: /localhome/inst/usr123/analysis/tmp_snakePipes/
verbose: false
workingdir: /scratch/adrija/02_projectname/data/chip-seq/test_ChIP/fastq_dedup_40

```bash
ls preprocessing_run-1.log
```

Error in rule clumpify:
    log: deduplicatedFASTQ/logs/sample_1.stdout, deduplicatedFASTQ/logs/sample_1.stderr (check log file(s) for error message)

```bash
less deduplicatedFASTQ/logs/sample_1.stderr
```

java -ea -Xmx30G -Xms30G -cp /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/9ed81382/opt/bbmap-38.61b-0/current/ clump.Clumpify -Xmx30G spany=t adjacent=t in=mergedFASTQ/sample_1_R1.fastq.gz out=deduplicatedFASTQ/sample_1_temp.fq.gz dupedist=40 threads=20
Executing clump.Clumpify [-Xmx30G, spany=t, adjacent=t, in=mergedFASTQ/sample_1_R1.fastq.gz, out=deduplicatedFASTQ/sample_1_temp.fq.gz, dupedist=40, threads=20]
Version 38.61

Read Estimate:          96471662
Memory Estimate:        48883 MB
Memory Available:       25151 MB
Set groups to 21
Executing clump.KmerSplit [in1=mergedFASTQ/sample_1_R1.fastq.gz, in2=, out=deduplicatedFASTQ/sample_1_temp_clumpify_p1_temp%_644d3a2e1af9951b.fq.gz, out2=, groups=21, ecco=false, addname=f, shortname=f, unpair=false, repair=f, namesort=f, ow=true, threads=20]

Set threads to 20
Input is being processed as unpaired
Made a comparator with k=31, seed=1, border=1, hashes=4
**[W::bgzf_read_block] EOF marker is absent. The input is probably truncated**
Time:                         	55.819 seconds.
Reads Processed:      48822k 	874.67k reads/sec
Bases Processed:       3634m 	65.11m bases/sec
Executing clump.KmerSort3 [in1=deduplicatedFASTQ/sample_1_temp_clumpify_p1_temp%_644d3a2e1af9951b.fq.gz, in2=, out=deduplicatedFASTQ/sample_1_temp.fq.gz, out2=, groups=21, ecco=f, addname=false, shortname=f, unpair=f, repair=false, namesort=false, ow=true, threads=20]

Set threads to 20
Making comparator.
Made a comparator with k=31, seed=1, border=1, hashes=4
Making 2 fetch threads.
Starting threads.
Fetching reads.
Fetched 2245630 reads: 	5.584 seconds.
Making clumps.
Clump time: 	0.946 seconds.
Writing.
Fetching reads.
Fetched 2238910 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.276 seconds.
Writing.
Fetching reads.
Fetched 2249074 reads: 	3.207 seconds.
Making clumps.
Clump time: 	0.533 seconds.
Writing.
Fetching reads.
Fetched 2665136 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.524 seconds.
Writing.
Fetching reads.
Fetched 2253275 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.320 seconds.
Writing.
Fetching reads.
Fetched 2264000 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.432 seconds.
Writing.
Fetching reads.
Fetched 2263658 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.312 seconds.
Writing.
Fetching reads.
Fetched 2353746 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.312 seconds.
Writing.
Fetching reads.
Fetched 2265709 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.275 seconds.
Writing.
Fetching reads.
Fetched 2348055 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.226 seconds.
Writing.
Fetching reads.
Fetched 2250244 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.403 seconds.
Writing.
Fetching reads.
Fetched 2463230 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.273 seconds.
Writing.
Fetching reads.
Fetched 2213538 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.384 seconds.
Writing.
Fetching reads.
Fetched 2246020 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.321 seconds.
Writing.
Fetching reads.
Fetched 2331425 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.293 seconds.
Writing.
Fetching reads.
Fetched 2298017 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.341 seconds.
Writing.
Fetching reads.
Fetched 2254336 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.317 seconds.
Writing.
Fetching reads.
Fetched 2547940 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.244 seconds.
Writing.
Fetching reads.
Fetched 2253960 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.252 seconds.
Writing.
Fetching reads.
No more reads to fetch.
Adding poison.
Fetched 2341690 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.270 seconds.
Writing.
Fetching reads.
Encountered poison; count=1
A fetch thread finished.
No more reads to fetch.
Adding poison.
Fetched 2474992 reads: 	0.000 seconds.
Making clumps.
Clump time: 	0.430 seconds.
Writing.
Closing fetch threads.
A fetch thread finished.
Closed fetch threads.
Waiting for writing to complete.
Write time: 	105.301 seconds.
Done!
Time:                         	767.457 seconds.
Reads Processed:        48822k 	63.62k reads/sec
Bases Processed:         3634m 	4.74m bases/sec

Reads In:             48822585
Clumps Formed:        23625693
Total time: 	823.997 seconds.
**sh: _R1.fastq.gz_optical_duplicatesdeduplicatedFASTQ/sample_1: No such file or directory**
**sh: _R1.fastq.gzdeduplicatedFASTQ/sample_1: No such file or directory**

```bash
less rawfastq/samples.tsv
```

sample_1_S2_L001_R1_001.fastq.gz      _R1     sample_1
sample_1_S2_L002_R1_001.fastq.gz      _R1     sample_1
sample_1_S2_L003_R1_001.fastq.gz      _R1     sample_1
sample_1_S2_L004_R1_001.fastq.gz      _R1     sample_1

**Comment by dpryan79** [comment] 2020-02-27 13:20
Can you rerun with `--verbose`?

**Comment by AdrijaK** [comment] 2020-02-28 11:45
Yes, here it is:

[preprocessing_run-3.log](https://github.com/maxplanck-ie/snakepipes/files/4266893/preprocessing_run-3.log)

**Comment by dpryan79** [comment] 2020-02-28 15:52
Hmm, this may have been resolved in the next release, since I can't reproduce the issue locally with the develop branch. We expect to have the next release available by Monday.

**Comment by AdrijaK** [comment] 2020-03-02 09:18
That's great, I am looking forward to trying it. Thank you.

**Comment by katsikora** [comment] 2020-03-02 10:17
The release is now available.

**Comment by AdrijaK** [comment] 2020-03-02 11:49
Noted, thank you.

**Comment by AdrijaK** [comment] 2020-03-10 15:01
I think I found the reason for the error message: this error appeared because one of the input fastq files was corrupt: 

```bash
cat ./FastQC/logs/FastQC.sample1_R1.err 
```
```
Started analysis of sample1_R1.fastq.gz
Failed to process file sample1_R1.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline '@NB501508:506:H5575BDXX:1:11108:21386:10317 1:N:0:GGCTAC' didn't start with '+'
	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:172)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:77)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Closed** 2020-03-10 15:02 UTC
