### ISSUE TITLE
HiC: All samples merged without considering group

### ISSUE THREAD

**Issue by millerh1** [maxplanck-ie/snakepipes#474] opened 2019-07-31 14:53 UTC
Hello!

I invoked HiC with a config.yaml file that included `merge_samples: true` and provided a `sampleSheet`:

```
name    condition
SRR7061198      siCTR
SRR7061199      siCTR
SRR7061200      siSA1
SRR7061201      siSA1
SRR7061202      siSA2
SRR7061203      siSA2
```

I expected HiC to merge the files based on the grouping I provided in the second column. Instead it merged all the samples together. Is this the expected behavior? 

Thank you,
Henry Miller

**Comment by LeilyR** [comment] 2019-07-31 15:00
It is supposed to merge by conditions, so in your case 2 replicates of each of your 3 groups should be merged together. please let me know if you observe otherwise.

**Comment by millerh1** [comment] 2019-07-31 15:06
All six of the samples were merged together in this case. Here is the pertinent section of the log file:

```
[Tue Jul 30 11:49:45 2019]
rule merge_matrices:
    input: HiC_matrices/SRR7061198_bs.h5, HiC_matrices/SRR7061199_bs.h5, HiC_matrices/SRR7061200_bs.h5, HiC_matrices/SRR7061201_bs.h5, HiC_matrices/SRR7061202_bs.h5, HiC_matrices/SRR7061203_bs.h5
    output: HiC_matrices/mergedSamples_merged_bs.h5
    log: HiC_matrices/logs/hicSumMatrices_merged_bs.out, HiC_matrices/logs/hicSumMatrices_merged_bs.err
    jobid: 25
    wildcards: group=merged

hicSumMatrices -m HiC_matrices/SRR7061198_bs.h5 HiC_matrices/SRR7061199_bs.h5 HiC_matrices/SRR7061200_bs.h5 HiC_matrices/SRR7061201_bs.h5 HiC_matrices/SRR7061202_bs.h5 HiC_matrices/SRR7061203_bs.h5 -o HiC_matrices/mergedSamples_merged_bs.h5 > HiC_matrices/logs/hicSumMatrices_merged_bs.out &> HiC_matrices/logs/hicSumMatrices_merged_bs.err
```

It sounds like this is not the expected behavior and it should have made 3 merged files, one per group as outlined in the sampleSheet.

Thank you,
Henry Miller

**Comment by LeilyR** [comment] 2019-07-31 15:17
Thanks for bringing it up! I will have a look and fix it in develop branch asap. I will update you as soon as it is ready.

**Comment by LeilyR** [comment] 2019-07-31 15:19
by the way, although it is a bit inconvenient but you can run the pipeline 3 times over each group for the time being.

**Comment by millerh1** [comment] 2019-07-31 15:20
Okay! Thank you for looking into this!

**Comment by LeilyR** [comment] 2019-08-02 09:18
Hi Henry,
I have run the pipeline  several times with different naming format including the exact same names you had used for your data and couldn't reproduce this issue. Are you using our develop? because no test have been failed on my side using the develop branch.

**Closed** 2019-08-03 21:55 UTC

**Comment by millerh1** [comment] 2019-08-06 20:10
So sorry I didn’t get back to you sooner – I was using the current conda version! I can try the development branch version.

**Comment by LeilyR** [comment] 2019-08-07 06:56
To be honest I don't think there is any differences between them. I cannot recall any recent changes on that, but yeah you could try develop if you want. Just be sure that your columns are tab separated!

**Comment by millerh1** [comment] 2019-08-07 17:10
They were – I checked that using cat -T command

I haven’t had a chance to run this again – but I will let you know when I do! I’m sure it’s an error I made somewhere in my command if it hasn’t been reproducible
