### ISSUE TITLE
rule create_annotation_bed failes with awk error

### ISSUE THREAD

**Issue by andreasd** [maxplanck-ie/snakepipes#643] opened 2020-06-03 14:28 UTC
hi! I'm testing snakepipes for mRNA-seq data and tried running it on a few test datasets. I have created indices for current hsa genomes which worked fine, but when running the pipeline I always get an error:

[Wed Jun  3 16:19:45 2020]
rule create_annotation_bed:
    input: /mnt/storage/workspace/projects/200602-mRNAseqTests/indices/annotation/genes.gtf
    output: Annotation/genes.annotated.bed
    jobid: 37

join -t $'      ' -o auto --check-order -1 4 -2 1 <(gtfToGenePred -ignoreGroupsWithoutExons /mnt/storage/workspace/projects/200602-mRNAseqTests/indices/annotation/genes.gtf /dev/stdout | genePredToBed /dev/stdin /dev/stdout | tr ' ' $'       ' | sort -k4,4) <(cat /mnt/storage/workspace/projects/200602-mRNAseqTests/indices/annotation/genes.gtf |  awk '$1!~"^#" && $3~"transcript|exon|start_codon|stop_codon|CDS"{print $0}' | tr -d "\";" |  awk '{pos=match($0,"gene_id.([^[:space:]]+)",a); if (pos!=0) gid=a[1];else exit 1;  pos=match($0,"transcript_id.([^[:space:]]+)",a); if (pos!=0) tid=a[1]; else tid=gid;  pos=match($0,"transcript_name.([^[:space:]]+)",a); if (pos!=0) tna=a[1]; else tna=tid;  pos=match($0,"transcript_[bio]*type.([^[:space:]]+)",a); if (pos!=0) tt=a[1]; else tt="NA";  pos=match($0,"gene_name.([^[:space:]]+)",a);  if (pos!=0) gna=a[1]; else gna=gid;  pos=match($0,"gene_[bio]*type.([^[:space:]]+)",a); if (pos!=0) gt=a[1]; else gt="NA";  pos=match($0,"transcript_support_level.([^[:space:]]+)",a); if (pos!=0) tsl=a[1]; else tsl="NA";  pos=match($0,"[[:space:]]level.([^[:space:]]+)",a); if (pos!=0) lvl=a[1] ; else lvl="NA";  pos=match($0,"tag.basic"); if (lvl!~"NA"){if (pos==0) basic="full"; else basic="basic"} else basic="NA";  OFS="\t"; print tid,tna,tt,gid,gna,gt,"gencode",basic,"transcript_support_level",tsl,"level",lvl}' |  sort | uniq | sort -k1,1) |  awk '{OFS="\t";print $2,$3,$4,$1,$5,$6,$7,$8,$9,$10,$11,$12,$1,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23}' > Annotation/genes.annotated.bed 
Activating conda environment: /home/andreas/miniconda3/envs/9a7ffacc01669a2865056de8624f82e9
awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,

this results in an empty Annotation/genes.annotated.bed file. I created the indices with:

createIndices -o indices --local -j40 --genome ftp://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz --gtf ftp://ftp.ensembl.org/pub/release-100/gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz GRCh38_release100

conda v4.8.1, most recent version of snakepipes.

would be very thankful for any hints on how to resolve/debug this.

**Comment by katsikora** [comment] 2020-06-03 14:38
Hi Andreas,

it looks like you are running some very old snakepipes version. This complex awk filtering has been replaced by python and the rule should be called now gtf_to_files .
What does <code>snakePipes version</code> return for you?

**Comment by andreasd** [comment] 2020-06-03 14:55
thank you for the quick response!

snakePipes version does not work - so indeed, it seems I got installed an older version. conda shows me:

snakepipes                1.3.0                      py_0    mpi-ie

I followed the instructions here: https://snakepipes.readthedocs.io/en/latest/content/setting_up.html

I'll check how and why I got this old version installed. Thanks again!

**Comment by katsikora** [comment] 2020-06-03 15:07
Oh I see, there is apparently some issue with conda resolving the snakepipes version to 1.3.0 when running <code>conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes</code>.

I don't know what this is caused by.

**Comment by andreasd** [comment] 2020-06-03 15:11
yes, I first thought it's my python version, but I still only get offered the 1.1 version of snakepipes.

i'm just trying to install 2.1.1 by explicitly asking for it:

conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes=2.1.1

let's see if that works. thanks for pointing me in the right direction!

**Comment by katsikora** [comment] 2020-06-03 15:35
you're welcome!

to specify snakePipes version, you'll have to go into two steps:
1)conda create -n myenv
2)conda install -n myenv ..... snakePipes==2.1.1

**Comment by katsikora** [comment] 2020-06-04 09:33
The latest documentation has been updated .

**Closed** 2020-06-05 11:12 UTC
Labels: bug, conda
