### ISSUE TITLE
DNA mapping error in rule Bowtie2

### ISSUE THREAD

**Issue by Leif78** [maxplanck-ie/snakepipes#793] opened 2021-11-30 12:36 UTC
Dear all,
I try DNA mapping with my commands:

DNA-mapping -i /home/leif/gamma_atac_experiment/raw_data -o /home/leif/gamma_atac_experiment/mapped_data -v --reads 'R1' 'R2' -j 12 --local --DAG --fastqc --qualimap --aligner Bowtie2 GRCz11

and get the output:

rule Bowtie2:
    input: FASTQ/atac_C2_R1.fastq.gz, FASTQ/atac_C2_R2.fastq.gz
    output: Bowtie2/atac_C2_.Bowtie2_summary.txt, Bowtie2/atac_C2_.sorted.bam
    log: Bowtie2/logs/atac_C2_.sort.log
    jobid: 161
    benchmark: Bowtie2/.benchmark/Bowtie2.atac_C2_.benchmark
    wildcards: sample=atac_C2_
    threads: 12

            TMPDIR=/data/extended/
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /home/leif/Dokumenter/BowtieIndex/genome -1 FASTQ/atac_C2_R1.fastq.gz -2 FASTQ/atac_C2_R2.fastq.gz               --fr             --rg-id atac_C2_             --rg DS:atac_C2_ --rg PL:ILLUMINA --rg SM:atac_C2_             -p 12             2> Bowtie2/atac_C2_.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/atac_C2_ -@ 2 -O bam - > Bowtie2/atac_C2_.sorted.bam 2> Bowtie2/logs/atac_C2_.sort.log;
            rm -rf $MYTEMP
            
Activating conda environment: /home/leif/anaconda3/envs/8730e82c
mktemp: failed to create directory via template ‘/data/extended//snakepipes.XXXXXXXXXX’: No such file or directory
[Tue Nov 30 11:39:07 2021]
Error in rule Bowtie2:
    jobid: 161
    output: Bowtie2/atac_C2_.Bowtie2_summary.txt, Bowtie2/atac_C2_.sorted.bam
    log: Bowtie2/logs/atac_C2_.sort.log (check log file(s) for error message)
    conda-env: /home/leif/anaconda3/envs/8730e82c
    shell:
        
            TMPDIR=/data/extended/
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /home/leif/Dokumenter/BowtieIndex/genome -1 FASTQ/atac_C2_R1.fastq.gz -2 FASTQ/atac_C2_R2.fastq.gz               --fr             --rg-id atac_C2_             --rg DS:atac_C2_ --rg PL:ILLUMINA --rg SM:atac_C2_             -p 12             2> Bowtie2/atac_C2_.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/atac_C2_ -@ 2 -O bam - > Bowtie2/atac_C2_.sorted.bam 2> Bowtie2/logs/atac_C2_.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/leif/gamma_atac_experiment/mapped_data/.snakemake/log/2021-11-30T113847.854261.snakemake.log

--- Config ---------------------------------------------------------------------
config file: /home/leif/gamma_atac_experiment/mapped_data/DNA-mapping.config.yaml
GCBias: False
NMaskedIndex: 
SNPfile: 
UMIBarcode: False
UMIDedup: False
UMIDedupOpts: None
UMIDedupSep: _
VCFfile: 
aligner: Bowtie2
alignerOpts: None
allele_mode: None
baseDir: /home/leif/anaconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes
bcPattern: NNNNCCCCCCCC
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: None
configFile: None
configMode: manual
createDAG: True
cutntag: False
dedup: False
downsample: None
emailAddress: None
emailSender: None
ext: .fastq.gz
fastqc: True
fragmentLength: 200
genome: GRCz11
indir: /home/leif/gamma_atac_experiment/raw_data
insertSizeMax: 1000
keepTemp: False
local: True
mapq: 0
mateOrientation: --fr
maxJobs: 12
max_thread: 25
mode: mapping
oldConfig: None
onlySSL: False
organismsDir: shared/organisms
outdir: /home/leif/gamma_atac_experiment/mapped_data
pipeline: dna-mapping
plotFormat: png
properPairs: False
qualimap: True
reads: ['R1', 'R2']
smtpPassword: None
smtpPort: 0
smtpServer: None
smtpUsername: None
snakemakeOptions:  --use-conda --conda-prefix /home/leif/anaconda3/envs 
strains: 
tempDir: /data/extended/
toolsVersion: True
trim: False
trimmer: cutadapt
trimmerOptions: None
verbose: True
workingdir: /home/leif/gamma_atac_experiment/mapped_data
-------------------------------------------------------------------------------- 

--- Genome ---------------------------------------------------------------------
config file: /home/leif/anaconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/organisms/GRCz11.yaml
blacklist_bed: 
bowtie2_index: /home/leif/Dokumenter/BowtieIndex/genome
bwa_index: /home/leif/Dokumenter/BWAIndex/genome.fa
bwameth_index: /home/leif/Dokumenter/BWAmethIndex/genome.fa
extended_coding_regions_gtf: /home/leif/Dokumenter/annotation/genes.slop.gtf
genes_bed: /home/leif/Dokumenter/annotation/genes.bed
genes_gtf: /home/leif/Dokumenter/annotation/genes.gtf
genome_2bit: /home/leif/Dokumenter/genome_fasta/genome.2bit
genome_dict: /home/leif/Dokumenter/genome_fasta/genome.dict
genome_fasta: /home/leif/Dokumenter/genome_fasta/genome.fa
genome_index: /home/leif/Dokumenter/genome_fasta/genome.fa.fai
genome_size: 1368780147
hisat2_index: /home/leif/Dokumenter/HISAT2Index/genome
ignoreForNormalization: 
known_splicesites: /home/leif/Dokumenter/HISAT2Index/splice_sites.txt
rmsk_file: 
spikein_blacklist_bed: 
spikein_genes_gtf: 
star_index: /home/leif/Dokumenter/STARIndex/
-------------------------------------------------------------------------------- 

--- Workflow parameters --------------------------------------------------------
samples: ['atac_10_1_', 'atac_10_2_', 'atac_10_3_', 'atac_1_1_', 'atac_1_2_', 'atac_1_3_', 'atac_40_1_', 'atac_40_2_', 'atac_40_3_', 'atac_C1_', 'atac_C2_', 'atac_C3_']
paired: True
read extension: ['R1', 'R2']
fastq dir: FASTQ
maximum insert size (Bowtie2 -X): 1000
-------------------------------------------------------------------------------- 

--- Environment ----------------------------------------------------------------
$TMPDIR:  /data/extended/
$HOSTNAME:  
-------------------------------------------------------------------------------- 

 !!! ERROR in DNA mapping workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Error: snakemake returned an error code of 1, so processing is incomplete!

I am grateful for any help to get further with the DNA mapping.

Best regards, Leif

**Comment by LeilyR** [comment] 2021-11-30 15:49
one comment which does not affect your error : Do not change the file suffix the default `reads: [_R1, _R2]` seems to match your data
the cause of your error seem to be the path to your temp directory, set ` TMPDIR=/data/extended/` to what is relevant to you

**Comment by Leif78** [comment] 2021-11-30 21:55
Thank you for kind answer.
How do you change temp directory. As I see it, it is not possible through the command DNA-mapping, and it is not possible to change it directly in the DNA-mapping.config.yaml file. Can you explain in more detail what I should do?

Thanks in advance,

hilsen Leif

**Comment by LeilyR** [comment] 2021-12-01 08:16
you need to use a customized config file and add it to your command line after -c . As far as I learnt about your data, the rest of the default values could stay, just set the temp path. You can read out documentation about using a customized config if you need more information. https://snakepipes.readthedocs.io/en/latest/content/workflows/DNA-mapping.html#dna-mapping
Hope it helps!

**Comment by LeilyR** [comment] 2021-12-08 12:27
I close this issue, feel free to re-open it if you still have any issue.

**Closed by LeilyR** 2021-12-08 12:27 UTC
