### ISSUE TITLE
Errors when using createIndices 

### ISSUE THREAD

**Issue by ppnin** [maxplanck-ie/snakepipes#384] opened 2019-02-08 13:37 UTC
Hi - I installed snakePipes today (no issues during the installation process) and created environments using the "snakePipes createEnvs" command. Now I am trying to create indices for human genome (version hg19), but I am getting various errors. Here is an example, below that I attach the whole log:

[Fri Feb  8 14:14:25 2019]
rule extendCodingRegions:
    input: /home/pavle/Documents/Data/HumanGenome/indices/annotation/genes.gtf
    output: /home/pavle/Documents/Data/HumanGenome/indices/annotation/genes.slop.gtf
    jobid: 7

/bin/bash: activate: No such file or directory
/bin/bash: line 1: gtfToGenePred: command not found
/bin/bash: line 1: genePredToBed: command not found
[Fri Feb  8 14:14:25 2019]
Error in rule gtf2BED:
    jobid: 6
    output: /home/pavle/Documents/Data/HumanGenome/indices/annotation/genes.bed
    conda-env: /home/pavle/miniconda3/envs/7950309be35c6ee5c992c38a2ad5bcba

[createIndices_run-1.log](https://github.com/maxplanck-ie/snakepipes/files/2845271/createIndices_run-1.log)

Any idea what is causing these errors? Thank you in advance.

Kind regards,
Pavle

**Comment by dpryan79** [comment] 2019-02-08 13:39
Make sure to run `snakePipes createEnvs` first.

**Comment by ppnin** [comment] 2019-02-08 13:41
Thanks - I did that, all the environments are installed

**Comment by dpryan79** [comment] 2019-02-08 13:47
Can you show me the output of `ls /home/pavle/miniconda3/envs/7950309be35c6ee5c992c38a2ad5bcba/bin` ?

**Comment by ppnin** [comment] 2019-02-08 13:49
Yes, here it is:
c_rehash  faToTwoBit  genePredToBed  gtfToGenePred  libpng16-config  libpng-config  my_print_defaults  mysql_config  openssl  perror  pngfix  png-fix-itxt

**Comment by ppnin** [comment] 2019-02-08 13:53
It looks bit tidier here:

c_rehash 
faToTwoBit  
genePredToBed  
gtfToGenePred  
libpng16-config  
libpng-config  
my_print_defaults  
mysql_config  
openssl  
perror  
pngfix  
png-fix-itxt

**Comment by dpryan79** [comment] 2019-02-08 13:54
Something is messed up in the conda environment such that snakeMake can't activate it. Can you `ln -s /home/pavle/miniconda3/bin/activate /home/pavle/miniconda3/envs/7950309be35c6ee5c992c38a2ad5bcba/bin` and see if that fixes it?

**Comment by ppnin** [comment] 2019-02-08 14:03
I did it now, unfortunately I'm getting similar errors. Here's an example with that environment:

Activating conda environment: /home/pavle/miniconda3/envs/7950309be35c6ee5c992c38a2ad5bcba
RuleException:
CalledProcessError in line 41 of /home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile:
Command 'source activate /home/pavle/miniconda3/envs/974433cd7e65c030b6b99bf2199033d1; set -euo pipefail;  
        samtools faidx /home/pavle/Documents/Data/HumanGenome/indicesTest/genome_fasta/genome.fa ' returned non-zero exit status 127.
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile", line 41, in __rule_fastaIndex
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.

**Comment by dpryan79** [comment] 2019-02-08 14:16
Looks like a similar step is needed in your other envs. I'm not sure what happened there. Out of curiousity, what conda version do you have (`conda --version`)?

**Comment by ppnin** [comment] 2019-02-08 14:24
Ok, I can try that. So for example, for the environment f417ca0eda671a6a276a01afcb820a70 I would create a symbolic link in the same way:

ln -s /home/pavle/miniconda3/bin/activate /home/pavle/miniconda3/envs/f417ca0eda671a6a276a01afcb820a70/bin  ?

My version of conda is 4.6.3

**Comment by dpryan79** [comment] 2019-02-08 14:34
Correct. I wonder if the issue is caused by the change in `conda` version. The 4.6 release is really recent and has caused a lot of headaches for various groups. Perhaps it's not playing nicely with snakemake.

**Comment by ppnin** [comment] 2019-02-08 14:44
Well.. in that case I hope that symlinking will solve the problem, I will let you know on Monday if the issue is still present. Regarding conda - do you maybe know if it's possible to download and install a previous version (one that works with snakmake, for instance)?

**Comment by dpryan79** [comment] 2019-02-08 14:46
You can try to `conda install -n base conda=4.5.13`, though that at least used to not work (that created problems for us in bioconda).

**Comment by steffenheyne** [comment] 2019-02-08 14:50
this might be related:
https://bitbucket.org/snakemake/snakemake/issues/1090/sge-conda-46-not-working

conda bin seems to be somewhere else

**Comment by ppnin** [comment] 2019-02-08 14:50
Right, I can try that if the previous step doesn't solve the problem. In that case, I guess I would have to re-install snakePipes and it's environments?

**Comment by dpryan79** [comment] 2019-02-08 14:50
@ppnin Unfortunately, yes :(

**Comment by steffenheyne** [comment] 2019-02-08 14:59
can you try to add "condabin" dir from miniconda install to your export PATH? 

should be in your case `/home/pavle/miniconda3//condabin/`

**Comment by ppnin** [comment] 2019-02-08 15:00
Ok, it might still be worth it if it fixes the problem :)

@steffenheyne Thanks, yeah -  it looks quite similar to my issue.

**Comment by ppnin** [comment] 2019-02-11 09:04
I don't know if this is expected behaviour for conda, but after I restarted the machine and ran ```createIndices``` again, snakemake seemed to be able to activate required environments - at least until  the step 14 (out of 15), where I got an error:

Activating conda environment: /home/pavle/miniconda3/envs/8de098feb44bcea20e863b9db7c5df22
/bin/bash: line 1: extract_splice_sites.py: command not found
[Mon Feb 11 09:27:58 2019]
Error in rule makeKnownSpliceSites:
    jobid: 10
    output: /home/pavle/Documents/Data/HumanGenome/indicesTest/HISAT2Index/splice_sites.txt
    conda-env: /home/pavle/miniconda3/envs/8de098feb44bcea20e863b9db7c5df22

RuleException:
CalledProcessError in line 128 of /home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile:
Command 'source activate /home/pavle/miniconda3/envs/8de098feb44bcea20e863b9db7c5df22; set -euo pipefail;  
        extract_splice_sites.py /home/pavle/Documents/Data/HumanGenome/indicesTest/annotation/genes.gtf > /home/pavle/Documents/Data/HumanGenome/indicesTest/HISAT2Index/splice_sites.txt ' returned non-zero exit status 127.
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile", line 128, in __rule_makeKnownSpliceSites
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job makeKnownSpliceSites since they might be corrupted:
/home/pavle/Documents/Data/HumanGenome/indicesTest/HISAT2Index/splice_sites.txt
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pavle/Documents/Data/HumanGenome/indicesTest/.snakemake/log/2019-02-09T134724.743385.snakemake.log
Error: snakemake returned an error code of 1, so processing is incomplete!


Does it indicate that the environment 8de098feb44bcea20e863b9db7c5df22 again could not be activated?    

Strangely, few lines above that I see: 

Activating conda environment: /home/pavle/miniconda3/envs/8de098feb44bcea20e863b9db7c5df22
[Mon Feb 11 09:27:57 2019]
Finished job 9.
13 of 15 steps (87%) done

and I guess that the environment was activated in the previous step.. 


@steffenheyne btw, I checked my PATH and condabin was already there.

**Comment by dpryan79** [comment] 2019-02-11 09:19
Is there an `extract_splice_sites.py` script in `/home/pavle/miniconda3/envs/8de098feb44bcea20e863b9db7c5df22/bin`? Maybe recent update to hisat2 in bioconda omitted it (if so, I can fix that).

**Comment by ppnin** [comment] 2019-02-11 09:23
No, ```extract_splice_sites.py``` is not there :)

**Comment by dpryan79** [comment] 2019-02-11 09:29
Gah, well there's the problem. Can you `source activate` that env and then post the output of `conda list | grep hisat`? I'll fix the recipe on bioconda.

**Comment by ppnin** [comment] 2019-02-11 09:43
Sure - here's the output, after I ```source activate``` that environment: 
 
hisat2
2.1.0
py27h2d50403_2
bioconda

**Comment by dpryan79** [comment] 2019-02-11 09:50
Interesting, the scripts got renamed (who though that was a good idea?) at some point. Can you just copy `hisat2_extract_splice_sites.py` to `extract_splice_sites.py` in that `bin/` directory? We need to fix this for the next release.

**Comment by dpryan79** [comment] 2019-02-11 10:02
Yes, you should be able to rerun it (it should just pick up from where it left off).

**Comment by ppnin** [comment] 2019-02-11 10:25
Right, I ran ```createIndices````again and I guess it picked up from the step 14, here's  ```Job counts```:

Job counts:
	count	jobs
	1	all
	1	makeKnownSpliceSites
	2

- and in the end I have 

[Mon Feb 11 11:04:30 2019]
Finished job 0.
2 of 2 steps (100%) done
Complete log: /home/pavle/Documents/Data/HumanGenome/indicesTest/.snakemake/log/2019-02-11T110417.404928.snakemake.log

so I suppose that the process finished OK. 
Thanks for the help!

**Comment by dpryan79** [comment] 2019-02-11 10:27
Thanks for reporting the issues! I'll try to push out a bugfix release this week to address them.

**Comment by ppnin** [comment] 2019-02-11 10:30
You're welcome. I will proceed now with the DNA-mapping and later ATAC-seq pipeline, will let now if there are issues.

**Comment by dpryan79** [comment] 2019-04-25 08:31
This should be fixed in release 1.2.0, which is coming out today.

**Closed by dpryan79** 2019-04-25 08:31 UTC
